### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/quarto-preview-colour#2]
- [x] Better recursive lookup for `Code`, _i.e._, currently not working for `BulletList`. #5 
- [ ] Support other colour code syntax:
  - [ ] Names one: `orange`.
  - [x] hex codes: `#441100` **-> Supported**.
  - [x] short hex codes: `#123` **-> Supported**.
  - [x] rgb: `rgb(10, 100, 200)` **-> Supported**.
  - [x] rgb with %: `rgb(100%, 20%, 100%)`.
  - [x] hwb: `hwb(135 0% 40%)`.
  - [x] hsl: `hsl(240, 100%, 50%)` **-> Supported**.
- [ ] Formats:
  - [x] LaTeX.
  - [x] Typst.
  - [x] Docx.
- [x] Make the colour preview symbol clickable to copy colour code.
- [x] Ensure screen readers can read everything properly (a11y).

Some reading: <https://dev.to/tigt/marking-up-colors-revisited-with-githubs-color-swatches-42eo>.
